/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class StyleConstants {
  public static DEFAULT_LAYOUT_FONT_COLOR: string = '#696969';
  public static DEFAULT_BACKGROUND_COLOR: string = '#F0EEEE';
  public static DEFAULT_DIALOG_FONT_COLOR: string = '#000000';
  public static DEFAULT_SETTING_PAGE_COLOR: string = '#FFFFFF';
  public static PERCENTAGE_100: string = '100%';
  public static PERCENTAGE_90: string = '90%';
  public static PERCENTAGE_85: string = '85%';
  public static PERCENTAGE_60: string = '60%';
  public static PERCENTAGE_30: string = '30%';
  public static PERCENTAGE_15: string = '15%';
  public static DEFAULT_APP_NAME_SIZE: number= 20;
  public static DEFAULT_APP_ITEM_WIDTH: number = 70;
  public static DEFAULT_APP_ITEM_HEIGHT: number = 95;
  public static DEFAULT_PIXEL_10: number = 10;
  public static DEFAULT_PIXEL_15: number = 15;
  public static DEFAULT_PIXEL_20: number = 20;
  public static DEFAULT_PIXEL_25: number = 25;
  public static DEFAULT_PIXEL_30: number = 30;
  public static DEFAULT_PIXEL_35: number = 35;
  public static DEFAULT_PIXEL_40: number = 40;
  public static DEFAULT_PIXEL_80: number = 80;
  public static DEFAULT_PIXEL_60: number = 60;
  public static DEFAULT_PIXEL_75: number = 75;
  public static DEFAULT_PIXEL_100: number = 100;
  public static DEFAULT_PIXEL_120: number = 120;
  public static DEFAULT_PIXEL_200: number = 200;
  public static DEFAULT_PIXEL_340: number = 340;
}