/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class StyleConstants {
  public static DEFAULT_FONT_COLOR: string = '#ffffff'
  public static DEFAULT_ICON: string = '/common/pics/icon.png'
  public static DEFAULT_BACKGROUND_IMAGE: string = '/common/pics/img_wallpaper_default.jpg'
  public static DEFAULT_APP_NAME_SIZE: number= 20;
  public static DEFAULT_APP_ITEM_WIDTH: number = 70;
  public static DEFAULT_APP_ITEM_HEIGHT: number = 95;
  public static PERCENTAGE_100: string = '100%'
  public static PERCENTAGE_85: string = '85%'
  public static PERCENTAGE_25: string = '25%'
  public static PERCENTAGE_15: string = '15%'
  public static PIXEL_200: string = '200px'
  public static PIXEL_150: string = '150px'
  public static PIXEL_50: string = '50px'
  public static LIGHT_BLACK: string = '#3c000000'
  public static DEFAULT_20: number = 20
  public static DEFAULT_80: number = 80
  public static DEFAULT_5: number = 5
  public static DEFAULT_30: number = 30
}