/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {

  //layout params - Icon
  static WHOLE_CONTAINER_MARGIN = 2
  static WHOLE_CONTAINER_WIDTH = 100
  static WHOLE_CONTAINER_HEIGHT = '50%'
  static PIC_CONTAINER_WIDTH = '70%'
  static PIC_CONTAINER_HEIGHT = '85%'
  //layout params - Pic
  static FULL_CONTAINER_WIDTH = '100%'
  static FULL_CONTAINER_HEIGHT = '100%'
  static BATTERY_BORDER_WIDTH = '88%'
  static BATTERY_BORDER_HEIGHT = '80%'
  static BATTERY_BORDER_RADIUS = 2
  static BATTERY_BORDER_MARGIN = 2
  static BATTERY_CONTENT_PADDING = 2
  static BATTERY_DECORATOR_WIDTH = '10%'
  static BATTERY_DECORATOR_HEIGHT = '50%'
  static BATTERY_DECORATOR_MARGIN = 2
  //layout params - Soc
  static SOC_FONT_SIZE = 16

  //value
  static BATTERY_LEVEL_LOW = 20

  static NONE = 0;
  static ENABLE = 1;
  static DISABLE = 2;
  static FULL = 3;
  static PERCENT_NUMBER = 100;
  static DEFAULT_PROGRESS = 100;

}