/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class StyleConstants {
  public static DEFAULT_FONT_COLOR: string = '#ffffff'
  public static DEFAULT_ICON: string = '/common/pics/icon.png'
  public static DEFAULT_BACKGROUND_IMAGE: string = '/common/pics/img_wallpaper.jpg'
  public static DEFAULT_APP_NAME_SIZE: number= 20;
  public static DEFAULT_APP_ITEM_WIDTH: number = 70;
  public static DEFAULT_APP_ITEM_HEIGHT: number = 95;
  public static PERCENTAGE_100: string = '100%'
  public static PERCENTAGE_85: string = '85%'
  public static PERCENTAGE_70: string = '70%'
  public static PERCENTAGE_15: string = '15%'
  public static DEFAULT_APP_IMAGE:string = '/common/pics/img_app_default.png'
  public static DEFAULT_DELETE_IMAGE:string = '/common/pics/ic_recent_delete.png'
  public static DEFAULT_BACKGROUND_IMAGE_RECENT:string = '/common/pics/ic_wallpaper_recent.jpg'
  public static APP_IMAGE_WIDTH: number = 240
  public static APP_IMAGE_HEIGHT: number = 430
  public static DEFAULT_NUMBER: number = 20
}