/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants of events that will be registered to system.
 */
const EventConstants = {
  EVENT_PACKAGE_ADDED: "usual.event.PACKAGE_ADDED",
  EVENT_PACKAGE_CHANGED: "usual.event.PACKAGE_CHANGED",
  EVENT_PACKAGE_REMOVED: "usual.event.PACKAGE_REMOVED"
}

export default EventConstants;